const staffTitleOptions = [
    "Administrative & Finance Manager",
    "Administrative Assistant Security",
    "Administrative Associate",
    "Budget Control Associate",
    "Budget Officer",
    "Budget Specialist",
    "Chief Child Protection",
    "Chief Education",
    "Chief Field Office",
    "Chief Field Operations",
    "Chief Health",
    "Chief Nutrition",
    "Chief of Communication",
    "Chief Planning, Monitoring & Evaluation",
    "Chief Social & Behavior Change",
    "Chief WASH",
    "Child Protection Cluster Coordinator",
    "Child Protection Officer",
    "Child Protection Specialist",
    "Cold Chain Officer",
    "Cold Chain Specialist",
    "Communication Specialist",
    "Construction Engineer",
    "Deputy Representative Operations",
    "Deputy Representative Programme",
    "Donor Relations Specialist",
    "Driver",
    "Education Manager",
    "Education Officer",
    "Education Specialist",
    "Emergency Officer",
    "Emergency Specialist",
    "Finance Associate",
    "Finance Specialist",
    "Health Officer",
    "Health Specialist",
    "Human Resources Associate",
    "Human Resources Officer",
    "Human Resources Specialist",
    "Immunization Manager",
    "Immunization Officer",
    "Immunization Specialist",
    "Implementing Partnership Mgmt Officer",
    "Implementing Partnership Mgmt Specialist",
    "Information Comm. Technology Associate",
    "Information Comm. Technology Manager",
    "Information Comm. Technology Officer",
    "Information Management Specialist",
    "Logistics Assistant",
    "Logistics Officer",
    "Logistics Specialist",
    "Monitoring & Evaluation Officer",
    "Nutrition Cluster Coordinator",
    "Nutrition Manager",
    "Nutrition Officer",
    "Nutrition Specialist",
    "Operations Associate",
    "Operations Officer",
    "Planning, Monitoring & Evaluation Specialist",
    "Programme Associate",
    "Programme Officer",
    "Programme Specialist",
    "Project Associate",
    "Radio Operator",
    "Representative",
    "Security Associate",
    "Security Officer",
    "Senior Administrative Associate",
    "Senior Driver",
    "Senior Finance Assistant",
    "Senior Finance Associate",
    "Senior Human Resources Associate",
    "Senior Info. Comm. Technology Associate",
    "Senior Logistics Associate",
    "Senior Operations Associate",
    "Senior Programme Specialist",
    "Senior Security Associate",
    "Senior Supply & Logistics Manager",
    "Senior Warehouse Associate",
    "Social & Behavior Change Officer",
    "Social & Behavior Change Specialist",
    "Social Policy Specialist",
    "Staff Security Specialist",
    "Supply & Logistics Associate",
    "Supply & Logistics Manager",
    "Supply Assistant",
    "Supply Associate",
    "Supply Officer",
    "Supply Specialist",
    "Travel Associate",
    "Warehouse Assistant",
    "WASH Manager",
    "Wash Officer",
    "WASH Specialist",
];

export default staffTitleOptions;
